apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: postgres-secrets
    creationPolicy: Owner
  data:
    - secretKey: CONNECTION_STRING
      remoteRef:
        key: {{ .Values.postgresSecretKeys.connectionString }}
