apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend_chart.fullname" . }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3001
  selector:
    app: {{ .Release.Name }}-api
