apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql-scripts
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
data:
  init_script.sql: |
    -- Your SQL initialization script here
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM pg_roles WHERE rolname = '{{ .Values.postgresql.username }}'
        ) THEN
            CREATE ROLE {{ .Values.postgresql.username }} WITH LOGIN PASSWORD '{{ .Values.postgresql.password }}';
        END IF;
    END $$;

    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM pg_database WHERE datname = '{{ .Values.postgresql.database }}'
        ) THEN
            CREATE DATABASE {{ .Values.postgresql.database }} WITH OWNER {{ .Values.postgresql.username }};
        END IF;
    END $$;

    GRANT ALL PRIVILEGES ON DATABASE {{ .Values.postgresql.database }} TO {{ .Values.postgresql.username }};

    CREATE TABLE country_and_capitals (
        id SERIAL PRIMARY KEY,
        country TEXT NOT NULL,
        capital TEXT NOT NULL
    );

    INSERT INTO country_and_capitals(country, capital) VALUES ('India', 'Delhi');
    INSERT INTO country_and_capitals(country, capital) VALUES ('China', 'Beijing');
    INSERT INTO country_and_capitals(country, capital) VALUES ('Bhutan', 'Thimpu');
    INSERT INTO country_and_capitals(country, capital) VALUES ('Russia', 'Moscow');
    INSERT INTO country_and_capitals(country, capital) VALUES ('America', 'Washington');
    INSERT INTO country_and_capitals(country, capital) VALUES ('England', 'London');
