apiVersion: v1
kind: Service
metadata:
  name: db
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: {{ .Release.Name }}-db
