# Create namespaces
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: namespace-a
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: namespace-b
# ---
# Deployment and Service for Service A
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
  namespace: namespace-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
    spec:
      containers:
        - name: app-a
          image: nginx  # Simple web server
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: namespace-a
spec:
  ports:
    - port: 80
  selector:
    app: app-a
---
# Deployment and Service for Service B
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b
  namespace: namespace-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-b
  template:
    metadata:
      labels:
        app: app-b
        role: frontend
    spec:
      containers:
        - name: app-b
          image: curlimages/curl  # Curl image for making requests
          command: ["sleep"]
          args: ["3600"]  # Keep the pod alive
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: namespace-b
spec:
  ports:
    - port: 80
  selector:
    app: app-b

